import type { Metadata } from "next";
import { Anek_Bangla } from "next/font/google";
import "@/styles/globals.css";
import { auth } from '../auth';


const anek_bangla = Anek_Bangla({
  subsets: ["latin", "latin-ext", "bengali"],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  console.log(session)
  return (
    <html lang="en">
      <body className={anek_bangla.className} suppressHydrationWarning>{children}</body>
    </html>
  );
}
